// Code generated by protoc-gen-go. DO NOT EDIT.
// source: song.proto

/*
Package go_micro_service_song is a generated protocol buffer package.

It is generated from these files:
	song.proto

It has these top-level messages:
	SongInfo
	ListRequest
	SongListResponse
	SearchRequest
	SearchResponse
	SongIdRequest
	SongResponse
*/
package go_micro_service_song

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SongInfo struct {
	SongId          int64  `protobuf:"varint,1,opt,name=song_id,json=songId" json:"song_id,omitempty"`
	SongName        string `protobuf:"bytes,2,opt,name=song_name,json=songName" json:"song_name,omitempty"`
	Artist          string `protobuf:"bytes,3,opt,name=artist" json:"artist,omitempty"`
	SongTimeMinutes string `protobuf:"bytes,4,opt,name=song_time_minutes,json=songTimeMinutes" json:"song_time_minutes,omitempty"`
	SongUrl         string `protobuf:"bytes,5,opt,name=song_url,json=songUrl" json:"song_url,omitempty"`
}

func (m *SongInfo) Reset()                    { *m = SongInfo{} }
func (m *SongInfo) String() string            { return proto.CompactTextString(m) }
func (*SongInfo) ProtoMessage()               {}
func (*SongInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *SongInfo) GetSongId() int64 {
	if m != nil {
		return m.SongId
	}
	return 0
}

func (m *SongInfo) GetSongName() string {
	if m != nil {
		return m.SongName
	}
	return ""
}

func (m *SongInfo) GetArtist() string {
	if m != nil {
		return m.Artist
	}
	return ""
}

func (m *SongInfo) GetSongTimeMinutes() string {
	if m != nil {
		return m.SongTimeMinutes
	}
	return ""
}

func (m *SongInfo) GetSongUrl() string {
	if m != nil {
		return m.SongUrl
	}
	return ""
}

type ListRequest struct {
	IdList []int64 `protobuf:"varint,1,rep,packed,name=id_list,json=idList" json:"id_list,omitempty"`
}

func (m *ListRequest) Reset()                    { *m = ListRequest{} }
func (m *ListRequest) String() string            { return proto.CompactTextString(m) }
func (*ListRequest) ProtoMessage()               {}
func (*ListRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListRequest) GetIdList() []int64 {
	if m != nil {
		return m.IdList
	}
	return nil
}

type SongListResponse struct {
	SongList []*SongInfo `protobuf:"bytes,1,rep,name=song_list,json=songList" json:"song_list,omitempty"`
}

func (m *SongListResponse) Reset()                    { *m = SongListResponse{} }
func (m *SongListResponse) String() string            { return proto.CompactTextString(m) }
func (*SongListResponse) ProtoMessage()               {}
func (*SongListResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SongListResponse) GetSongList() []*SongInfo {
	if m != nil {
		return m.SongList
	}
	return nil
}

type SearchRequest struct {
	Keyword string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
}

func (m *SearchRequest) Reset()                    { *m = SearchRequest{} }
func (m *SearchRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchRequest) ProtoMessage()               {}
func (*SearchRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *SearchRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

type SearchResponse struct {
	SongList []*SongInfo `protobuf:"bytes,1,rep,name=song_list,json=songList" json:"song_list,omitempty"`
}

func (m *SearchResponse) Reset()                    { *m = SearchResponse{} }
func (m *SearchResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchResponse) ProtoMessage()               {}
func (*SearchResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SearchResponse) GetSongList() []*SongInfo {
	if m != nil {
		return m.SongList
	}
	return nil
}

type SongIdRequest struct {
	SongId int64 `protobuf:"varint,1,opt,name=song_id,json=songId" json:"song_id,omitempty"`
}

func (m *SongIdRequest) Reset()                    { *m = SongIdRequest{} }
func (m *SongIdRequest) String() string            { return proto.CompactTextString(m) }
func (*SongIdRequest) ProtoMessage()               {}
func (*SongIdRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SongIdRequest) GetSongId() int64 {
	if m != nil {
		return m.SongId
	}
	return 0
}

type SongResponse struct {
	SongInfo  *SongInfo `protobuf:"bytes,1,opt,name=song_info,json=songInfo" json:"song_info,omitempty"`
	IsSuccess bool      `protobuf:"varint,2,opt,name=is_success,json=isSuccess" json:"is_success,omitempty"`
}

func (m *SongResponse) Reset()                    { *m = SongResponse{} }
func (m *SongResponse) String() string            { return proto.CompactTextString(m) }
func (*SongResponse) ProtoMessage()               {}
func (*SongResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SongResponse) GetSongInfo() *SongInfo {
	if m != nil {
		return m.SongInfo
	}
	return nil
}

func (m *SongResponse) GetIsSuccess() bool {
	if m != nil {
		return m.IsSuccess
	}
	return false
}

func init() {
	proto.RegisterType((*SongInfo)(nil), "go.micro.service.song.SongInfo")
	proto.RegisterType((*ListRequest)(nil), "go.micro.service.song.ListRequest")
	proto.RegisterType((*SongListResponse)(nil), "go.micro.service.song.SongListResponse")
	proto.RegisterType((*SearchRequest)(nil), "go.micro.service.song.SearchRequest")
	proto.RegisterType((*SearchResponse)(nil), "go.micro.service.song.SearchResponse")
	proto.RegisterType((*SongIdRequest)(nil), "go.micro.service.song.SongIdRequest")
	proto.RegisterType((*SongResponse)(nil), "go.micro.service.song.SongResponse")
}

func init() { proto.RegisterFile("song.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 393 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x53, 0xcf, 0x4f, 0xf2, 0x40,
	0x10, 0xa5, 0xc0, 0x57, 0xe8, 0xf0, 0xf1, 0xfd, 0xd8, 0x44, 0xad, 0x18, 0x23, 0x59, 0x51, 0xd1,
	0x43, 0x0f, 0x78, 0xf5, 0x6e, 0x48, 0x94, 0x98, 0xa2, 0x31, 0x31, 0x26, 0x4d, 0x6d, 0x17, 0xdc,
	0x40, 0xbb, 0xb8, 0xbb, 0xd5, 0xf8, 0xa7, 0x78, 0xf2, 0x5f, 0x35, 0xbb, 0x4b, 0x49, 0x13, 0x01,
	0x3d, 0x78, 0x9c, 0x99, 0x37, 0x6f, 0xde, 0xbc, 0x9d, 0x05, 0x10, 0x2c, 0x1d, 0x7b, 0x33, 0xce,
	0x24, 0x43, 0x1b, 0x63, 0xe6, 0x25, 0x34, 0xe2, 0xcc, 0x13, 0x84, 0x3f, 0xd3, 0x88, 0x78, 0xaa,
	0x88, 0xdf, 0x2d, 0xa8, 0x0f, 0x59, 0x3a, 0xee, 0xa7, 0x23, 0x86, 0xb6, 0xa0, 0xa6, 0x92, 0x01,
	0x8d, 0x5d, 0xab, 0x6d, 0x75, 0x2b, 0xbe, 0xad, 0xc2, 0x7e, 0x8c, 0x76, 0xc0, 0xd1, 0x85, 0x34,
	0x4c, 0x88, 0x5b, 0x6e, 0x5b, 0x5d, 0xc7, 0xaf, 0xab, 0xc4, 0x20, 0x4c, 0x08, 0xda, 0x04, 0x3b,
	0xe4, 0x92, 0x0a, 0xe9, 0x56, 0x74, 0x65, 0x1e, 0xa1, 0x13, 0xf8, 0xaf, 0x9b, 0x24, 0x4d, 0x48,
	0x90, 0xd0, 0x34, 0x93, 0x44, 0xb8, 0x55, 0x0d, 0xf9, 0xab, 0x0a, 0xd7, 0x34, 0x21, 0x97, 0x26,
	0x8d, 0xb6, 0x41, 0xf3, 0x05, 0x19, 0x9f, 0xba, 0xbf, 0x34, 0x44, 0x2b, 0xb9, 0xe1, 0x53, 0x7c,
	0x08, 0x8d, 0x0b, 0x2a, 0xa4, 0x4f, 0x9e, 0x32, 0x22, 0xa4, 0xd2, 0x48, 0xe3, 0x60, 0xaa, 0xc6,
	0x59, 0xed, 0x8a, 0xd2, 0x48, 0x63, 0x55, 0xc7, 0x57, 0xf0, 0x4f, 0x2d, 0x62, 0xb0, 0x62, 0xc6,
	0x52, 0x41, 0xd0, 0xd9, 0x5c, 0xf7, 0x02, 0xde, 0xe8, 0xed, 0x79, 0x4b, 0x8d, 0xf0, 0x72, 0x13,
	0xcc, 0x62, 0x9a, 0xf1, 0x18, 0x9a, 0x43, 0x12, 0xf2, 0xe8, 0x31, 0x9f, 0xed, 0x42, 0x6d, 0x42,
	0x5e, 0x5f, 0x18, 0x37, 0xfe, 0x38, 0x7e, 0x1e, 0xe2, 0x01, 0xfc, 0xc9, 0xa1, 0x3f, 0x32, 0xba,
	0x0b, 0x4d, 0x9d, 0x8d, 0x0b, 0x6b, 0x2f, 0x7d, 0x1a, 0x3c, 0x81, 0xdf, 0x0a, 0xf9, 0x69, 0x2e,
	0x4d, 0x47, 0x4c, 0x43, 0xbf, 0x3b, 0x57, 0x5f, 0xc0, 0x2e, 0x00, 0x15, 0x81, 0xc8, 0xa2, 0x88,
	0x08, 0xa1, 0x5f, 0xba, 0xee, 0x3b, 0x54, 0x0c, 0x4d, 0xa2, 0xf7, 0x56, 0x86, 0xaa, 0xea, 0x42,
	0xb7, 0x60, 0x9b, 0x7d, 0x51, 0x67, 0x15, 0x79, 0xd1, 0xb9, 0xd6, 0xc1, 0x17, 0x28, 0x23, 0x1e,
	0x97, 0xd0, 0x1d, 0x34, 0xce, 0x89, 0x5c, 0x5c, 0x64, 0x67, 0x9d, 0xf4, 0xdc, 0x9c, 0xd6, 0xfe,
	0x1a, 0x54, 0x81, 0xfb, 0x7e, 0xc1, 0xad, 0x3c, 0x46, 0x78, 0x45, 0x57, 0xe1, 0xda, 0x5a, 0x47,
	0x6b, 0x98, 0x8b, 0x97, 0x86, 0x4b, 0x0f, 0xb6, 0xfe, 0x67, 0xa7, 0x1f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0xc8, 0xb9, 0x52, 0xee, 0x75, 0x03, 0x00, 0x00,
}
